config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  root 'inicio#index'
  get 'inicio/index'
  resources :sale_productos
  resources :productos
  resources :sales
  resources :clientes

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">Valentina's</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%=clientes_path%>">Clientes</a></li>
        <li><a href="<%=productos_path%>">Productos</a></li>
        <li><a href="<%=sales_path%>">Ventas</a></li>
        <li><a href="<%=sale_productos_path%>">Detalle de Ventas</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if usuario_signed_in? %>
        <li><a href="<%= edit_usuario_registration_path(current_usuario) %>">Editar Perfil</a></li>
        <li><a href="<%= destroy_usuario_session_path %>",data-method="delete">Cerrar Sesion</a></li>
        <% else %>
        <li><a href="<%= new_usuario_session_path %>">Ingresar</a></li>
        <li><a href="<%= new_usuario_registration_path %>">Registrarse</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>