config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  root 'inicio#index'
  get 'inicio/index'
  resources :sale_productos
  resources :productos
  resources :sales
  resources :clientes

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :usuario
  has_many :sale_producto
  has_many :producto, :through => :sale_producto
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:show, :index]
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @productos = @sale.producto.all
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:folio, :fechacompra, :precio, :cantidad, :cliente_id)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :folio %><br>
    <%= f.number_field :folio %>
  </div>
  <div class="field">
    <%= f.label :fechacompra %><br>
    <%= f.date_select :fechacompra %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :cliente_id %><br>
  <%= f.select( "cliente_id",Cliente.all.collect{|l| [ l.nombre, l.id ] }, {include_blank: 'Seleccione Cliente'}) %>
  </div>

  <%= f.hidden_field :usuario_id, :value => current_usuario.id   %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Folio</th>
      <th>Fechacompra</th>
      <th>Precio</th>
      <th>Cantidad</th>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.folio %></td>
        <td><%= sale.fechacompra %></td>
        <td><%= sale.precio %></td>
        <td><%= sale.cantidad %></td>
        <td><%= sale.cliente.nombre %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Folio: <%= @sale.folio %></h2>
<h3>Fechacompra: <%= @sale.fechacompra %></h3>
<h3>Precio: <%= @sale.precio %></h3>
<h3>Cantidad: <%= @sale.cantidad %></h3>
<h3>Cliente: <%= @sale.cliente.nombre %></h3>

<h2>Productos de las Ventas:</h2>
<% @productos.each do |producto| %>
  <strong>Nombre:</strong>
  <%= producto.nombre %>
  <strong>Precio:</strong>
  <%= producto.precio %>
  <strong>Descripcion:</strong>
  <%= producto.descripcion %>
  <br>
<% end %>
<br>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>